### ISSUE TITLE
Error when game finishes and i replay the game..

### ISSUE THREAD

**Issue by chiru9670** [XI-E/Snake-Xenzia#1]
pos_key is a matrix corresponding to each and every position on the screen. I'm  using it to store direction values of the head corresponding to its position so that when the tail arrives there, it will use the direction value stored there to proceed.
the thing is, if i replay the game, the matrix pos_key already has some stored values in it. how do i reinitialize it to all " "?
note: by observation, i found that if an array, matrix etc is defined uninitialized, by default, it has " " stored at its every element if its type is char, and 0 if its type is int.

**Comment by arpit-saxena** [comment]
> note: by observation, i found that if an array, matrix etc is defined uninitialized, by default, it has " " stored at its every element if its type is char, and 0 if its type is int.

This might be true for turbo c++ but all elements of an uninitialised array have garbage values
Eg:
```c++
#include <iostream>

using namespace std;

int main(void)
{
        int a[20];
        for(int i = 0; i < 20; i++)
        {
                cout << a[i] << endl;
        }
        return 0;
}
```
gave output as
```
0
0
65535
1
1623115024
32766
4196670
0
2
0
4196749
0
0
0
0
0
4196672
0
4196240
0
```
when I ran it on the terminal. It gives different garbage values when ran different times

**Comment by chiru9670** [comment]
fixed!!
I'm just reinitializing the matrix at the start of main() using a for loop and the 2d array parameters arr_x and arr_y.(which are macros)
