### ISSUE TITLE
How do i use arrow keys in my program?

### ISSUE THREAD

**Issue by chiru9670** [XI-E/Snake-Xenzia#2]
I'm using wasd for movement. I thought that arrow keys have well defined ascii codes, so i thought i'd replace them after my program is written.
but now i see arrow keys aren't that simple, so, well, HELP!!

**Comment by arpit-saxena** [comment]
I don't understand your code properly enough to edit it, though here is a simple code for arrow keys:

```c++
char c = getch();
while(c != 27)
{
	if(c == 0)
	{
		c = getch();
		switch(c)
		{
			case 'H':
				cout << "Up\n";
				break;
			case 'P':
				cout << "Down\n";
				break;
			case 'K':
				cout << "Left\n";
				break;
			case 'M':
				cout << "Right\n";
				break;
		}
	}
	c = getch();
}
```

27 is key code for esc. So, this runs till escape key is pressed

**Comment by sankalpgambhir** [comment]
I'm already working on that

**Comment by chiru9670** [comment]
OK I fixed it.   :-)
I just declared another function getdir() which converts arrow key input into w, a, s, d.
